### ISSUE TITLE
Backward import parsing 

### ISSUE THREAD

**Issue by gurmukhp** [marklagendijk/WinLess#18]
Hi,

WinLess is an incredible tool, one which is saving me lots of time. I would like to further increase the speed of my workflow and was wondering if Winless 1.5.3 supports backward import parsing? Having a look at the homepage, it looks like it does, but I cannot seem to activate this feature.

I have one ns.less file that has the following contents:

// Base Files
@import url("../../reset.less");
@import url("../../main.less");

If I make changes to ns.less then the file compiles immediately, however, if I compile reset.less or main.less then the file doesnt compile. I have to resave ns.less to re-compile.

Is there a way in which I can get around this?

Many thanks :)

**Comment by marklagendijk** [comment]
You have to make sure that you also add those imported files to WinLess. WinLess only watches files which you add.

**Comment by gurmukhp** [comment]
Hi Mark, thanks for your reply,

If I add those files, then WinLess begins to compile each .less file separately. I only want a few of the .less files to be compiled. 

I have tried unticking the files not needed, but this doesnt seem to work either. ie when I update the files, the main .less doesnt get compiled

**Comment by marklagendijk** [comment]
> I have tried unticking the files not needed, but this doesnt seem to work either. ie when I update the files, the main .less doesnt get compiled

That should work. Are you sure that it doesn't?

**Comment by gurmukhp** [comment]
Hi Mark,

I've tried a few times and it doesn't work. It seems that the imported
files are not being analysed and included in the main less file.

No worries, I will use a batch script on save instead.

On 15 May 2012 19:57, Mark Lagendijk <
reply@reply.github.com

**Comment by marklagendijk** [comment]
If you can send me an example code which shows this problem, I can take a look at it. You can email it to info@winless.org.

**Comment by marklagendijk** [comment]
I am still looking for simple testcase which demonstrates this problem.

**Comment by renemaas** [comment]
You cannot use mapped network storages. You have to use the UNC syntax (http://www.johnrellis.com/psedbtool/photoshop-elements-faq.htm#_Watching_Network_Folders).
Maybe there is a possibility to automatically change the path from a mapped storage to the UNC syntax.

E.g.: \\server\dir\dir

**Comment by marklagendijk** [comment]
It seems that the issue is indeed related to network drives. But apparently watching a network folder DOES work, because otherwise the automatic compile wouldn't work at all (instead of just not working for backwards import compiling).
I think the issue may be in the code which checks maps `@import` statements to files. At least I now know where to look and how to reproduce the problem. Tnx!

**Comment by marklagendijk** [comment]
I have done a simple test, but am not able to reproduce the problem.

main.less:

``` css
@import "variables.less";

.container{
    color: @color;
    width: @width;
    height: 502px;
}
```

variables.less:

``` css
@color: blue;
@width: 202px;
```

First I tested on my local drive. Whenever I save either `main.less` or `variables.less` main.less gets recompiled.
After that I did the same test on a network drive. I tried both using the full path `\\myServer\mark\LESS test` and mapping the location as a network drive `G:\LESS test`.
In both cases the automatic compiling still worked properly.

@renemaas (or someone else), can you give me more information on how to reproduce this problem?

**Comment by mgdodge** [comment]
I can confirm the bug on my freshly installed copy of WinLess. To reproduce, here are some sample files:

~\some-dir\css\less\styles.less (compiles to ~\some-dir\css\styles.css):

``` css
// Define colors and styles
@red: #F00;
@small: 10px;
.em {
  font-style: italic;
}

// Import layout
@import url("layout.less");
```

~\some-dir\css\less\layout.less (not compiled, only imported):

``` css
body {
  background: #FFF;
  padding: 0; margin: 0;
  font-size: 12px;
  .red {
    color: @red;
    .small {
      font-size: @small;
      color: #F99;
    }
  }
  .small {
    font-size: @small;
  }
}

```

Add ~\some\dir\css\less to WinLess (I did via drag/drop) and uncheck layout.less (never compiled, only imported). Make a change directly to styles.less and the files compile as expected. Make a change to layout.less and the compile never happens.

While writing this comment up, I think I found out how to root out the problem (not being a .net programmer, however, I can't fix it). If you change the last line of styles.less thus:

``` css
@import "layout.less"; // used to be url("layout.less");
```

the compile process happens as you would expect. It seems that there is a problem with the 'url(...)' syntax of importing. The syntax works fine in other compilers in use around my office (PC and Mac) all using the latest version of less.js, so it seems the problem is not less itself.

**Comment by marklagendijk** [comment]
@mikezilla that helps, tnx!
I fixed the RegEx which finds the `@import` to be more flexible. It should now work with all correct syntaxes.

The fix will be released with 1.8.1.

**Comment by marklagendijk** [comment]
I totally forgot about this fix. Otherwise I would have released 1.8.1 much sooner.
Anyway, 1.8.1 has now been released, and this issue should be fixed now.

**Comment by cardeo** [comment]
I'm running version 1.8.1 but I'm still having this compile problem that mikezilla outlined
